version: "3.7"

services:
  muxy:
    build:
      context: ./muxy/
    command: gunicorn muxy.wsgi:application --workers 3 --bind 0.0.0.0:8000
    env_file:
      - ./muxy/.env
    volumes:
      - ./muxy/:/usr/src/app
    stdin_open: true
    tty: true
    ports:
      - 8000:8000

  nginx-rtmp:
    build:
      context: ./nginx-rtmp/
    ports:
      - 1935:1935
    depends_on:
      - muxy

  owncast:
    image: owncast/owncast:latest
    ports:
      - 8080:8080
      - 1936:1935
