version: "3.7"

services:
  owncast:
    image: owncast/owncast:latest
    ports:
      - 8080:8080
      - 1936:1935

  muxy:
    build:
      context: ./muxy/
    command: gunicorn muxy.wsgi:application --workers 3 --bind 0.0.0.0:8000
    volumes:
      - ./muxy/:/usr/src/app
    stdin_open: true
    tty: true
    ports:
      - 8000:8000

  nginx-rtmp:
    build:
      context: ./nginx-rtmp/
    ports:
      - 1935:1935
    depends_on:
      - muxy

  web:
    build:
      context: ./web/
    volumes:
      - ./web/:/app
    ports:
      - 3000:3000
    depends_on:
      - muxy
      - owncast
