version: "3.7"
include:
  - docker-compose.base.yml

services:
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile.dev
    volumes:
      - ./web/src:/app/src
    ports:
      - 3000:3000
    depends_on:
      - muxy
      - chat
