version: "3.7"

services:
  muxy:
    build:
      context: ./muxy/
    volumes:
      - ./muxy/:/app
      - ./data/muxy:/data
    environment:
      - DB_PATH=/data/db.sqlite3
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    command: gunicorn muxy.wsgi:application --workers 3 --bind 0.0.0.0:8000
    restart: always

  nginx-rtmp:
    build:
      context: ./nginx-rtmp/
    ports:
      - 1935:1935
      - 8080:8080
    env_file:
      - ./nginx-rtmp/.env
    volumes:
      - ./data/recordings:/recordings
      - ./data/hls:/mnt/hls
      - ./data/log:/mnt/log
    restart: always
    depends_on:
      - muxy
      - main-owncast
      - test-owncast

  main-owncast:
    image: owncast/owncast:latest
    ports:
      - 8081:8080
    volumes:
      - ./data/main-owncast:/app/data
    restart: always

  test-owncast:
    image: owncast/owncast:latest
    ports:
      - 8082:8080
    volumes:
      - ./data/test-owncast:/app/data
    restart: always

  web:
    build:
      context: ./web/
    ports:
      - 3000:80
    restart: always
    depends_on:
      - muxy
