version: "3.7"

services:
  muxy:
    build:
      context: ./muxy/
    volumes:
      - ./muxy/:/app
      - ./data/muxy:/data/db
      - ./data/recordings:/data/recordings:ro
    environment:
      - DB_PATH=/data/db/db.sqlite3
      - RECORDINGS_ROOT=/data/recordings
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    command: gunicorn muxy.wsgi:application --workers 3 --bind 0.0.0.0:8000
    hostname: muxy.eulerroom.com
    restart: always

  nginx-rtmp:
    build:
      context: ./nginx-rtmp/
    ports:
      - 1935:1935
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./nginx-rtmp/nginx.conf.template:/tmp/nginx.conf.template:ro
      - ./nginx-rtmp/stat.xsl:/usr/local/nginx/html/stat.xsl:ro
      - ./data/recordings:/recordings
    restart: always
    depends_on:
      - main-owncast
      - test-owncast

  main-owncast:
    build:
      context: ./owncast/
    ports:
      - 8081:8081
    env_file:
      - .env
    volumes:
      - ./data/main-owncast:/app/data
    command: -streamkey ${MAIN_STREAM_KEY} -webserverport 8081 -rtmpport 1935
    restart: always

  test-owncast:
    build:
      context: ./owncast/
    ports:
      - 8082:8082
    env_file:
      - .env
    volumes:
      - ./data/test-owncast:/app/data
    command: -streamkey ${TEST_STREAM_KEY} -webserverport 8082 -rtmpport 1935
    restart: always
