version: "3.7"

services:
  muxy:
    build:
      context: ./muxy/
    volumes:
      - ./muxy/:/app
      - ./data/muxy:/data
    environment:
      - DB_PATH=/data/muxy.db
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    command: gunicorn muxy.wsgi:application --workers 3 --bind 0.0.0.0:8000

  nginx-rtmp:
    build:
      context: ./nginx-rtmp/
    ports:
      - 1935:1935
    depends_on:
      - muxy

  web:
    build:
      context: ./web/
    volumes:
      - ./web/src:/app/src
    ports:
      - 5173:5173
    depends_on:
      - muxy
